### ISSUE TITLE
Display affiliate information with affiliate cookie

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-info#11]
>We would like to have the affiliate information show on each page when there is a referrer. We have been able to make that happen, however, it sometimes goes away when we change pages. Is it possible to have that information stay on every page as the visitor browses the site? 

If an affiliate cookie is already generated with in the referred user's browser, then this customer would like affiliate information to continue to be displayed without the need for an affiliate URL.

Ticket: https://secure.helpscout.net/conversation/554127502/79685/.

**Comment by amdrew** [comment]
Is this a request for the affiliate information to persist across pages? If so, this is how it currently works - the add-on displays information based off the affiliate ID stored in the cookie. If it's not working for the customer then it may be caching issue. Do you see the affiliate information persist across pages in your testing?

**Comment by michaelbeil** [comment]
I do not see this in my testing.

**Comment by amdrew** [comment]
Ok, will test tomorrow to see if this is still working as intended

**Comment by michaelbeil** [comment]
That sounds good!

**Comment by michaelbeil** [comment]
I cannot replicate this issue now either. All good here!

**Comment by michaelbeil** [comment]
A user is experiencing this issue: https://secure.helpscout.net/conversation/756665100/98779?folderId=634609

**Comment by michaelbeil** [comment]
>I just tested this by visting https://veganlaunch.com/affiliate-test/?ref=1 while logged in as admin. The test affiliate is not the admin. The reason I did this is because logged in as Admin, no WordPress pages are cached.

>The good news is that the feature works as expected in this test, so you are correct that there is some issue regarding this functionality and caching. 

I asked if WPEngine is able to adjust the caching for this.

Everything seems to be good, otherwise.
