### ISSUE TITLE
Allow language translations to be handled by WP repo

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-info#14]
We need to update this plugin so the language files are handled by the WP repo. Similar to: easydigitaldownloads/edd-featured-downloads#9

**Comment by DrewAPicture** [comment]
Note: Ask @DrewAPicture how to best accomplish this.

**Comment by dbeja** [comment]
PR: #25

**Comment by DrewAPicture** [comment]
Merged #25 against `release/1.0.6`
