### ISSUE TITLE
Compatibility with Custom affiliate slugs and Direct Link Tracking

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-info#6]
A customer has reported that when a custom affiliate slug is used the affiliate info is not showing until the page is refreshed. Might affect DLT also.

**Comment by sumobi** [comment]
Haven't been able to replicate thus far, could be an issue with customer's site.

**Comment by sumobi** [comment]
Replicated

**Comment by sumobi** [comment]
I've first introduced a new method in Custom Affiliate Slugs that retrieves an affiliate's ID based on the custom slug: https://github.com/AffiliateWP/affiliatewp-custom-affiliate-slugs/commit/77119525f5150aba956bd6d23cbf951316a8ee2a

The PR uses that to fix this issue
