### ISSUE TITLE
Referral variable does no longer exists in query vars

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-info#9]
When a visitor first lands on a page using a pretty affiliate link, the affiliate ID or username is retrieved from the query vars. From there on, the cookie value is used since it's then set.

The value (ID or username) is retrieved like this:

https://github.com/AffiliateWP/affiliatewp-affiliate-info/blob/master/includes/class-functions.php#L150-L154

If the referral variable was `ref` it essentially retrieves the value with `$wp_query->query['ref]`. This no longer works and the referral variable does not appear in `$wp_query->query`. 

If I roll back to version `2.0.10.1` of AffiliateWP and flush the permalinks I can clearly see the referral variable exists, however it's not there with any newer version. Not even the first commit after.

To see it _working_:

1. Roll back to version `2.0.10.1` of AffiliateWP
2. Use the following code:

``` php
function affwp_custom_get_query_var() {

	global $wp_query;

	$referral_var = affiliate_wp()->tracking->get_referral_var();

	var_dump( $wp_query->query[$referral_var] );

}
add_action( 'template_redirect', 'affwp_custom_get_query_var' );
```
3. Flush permalinks
4. Go to a URL such like `/ref/2/`
5. The result will be a string of `2`.

To replicate the issue:

1. Go to any newer version of AffiliateWP
2. Flush permalinks
3. Visit same URL
4. The result is `null`

**Comment by amdrew** [comment]
@AffiliateWP/core Any thoughts?

**Comment by pippinsplugins** [comment]
@amdrew does the following work for you?

```php
function affwp_custom_get_query_var() {

	global $wp_query;

	$affiliate_id = affiliate_wp()->tracking->get_fallback_affiliate_id();

	var_dump( $affiliate_id );

}
add_action( 'template_redirect', 'affwp_custom_get_query_var' );
```

**Comment by amdrew** [comment]
The above works. As Pippin suggested in Slack the solution here would be to first use the get_affiliate_id() method and failing that, the `get_fallback_affiliate_id()` method.

**Comment by amdrew** [comment]
Going to put something together and push out an update soon-ish.

**Comment by michaelbeil** [comment]
Ticket: https://secure.helpscout.net/conversation/409004054/64353/?folderId=634609.

**Comment by amdrew** [comment]
Tested this extensively to make sure it worked with custom affiliate slugs, credit last referrer etc. Have pushed out an update.

**Comment by pippinsplugins** [comment]
@amdrew please remove the remaining items from the 1.0.4 milestone and adjust the milestones accordingly. Once a release goes out, there should not be any open issues on the milestone.
